version: '3'
services:
  restapi:
    build: .
    environment:
      DBHOST: ${DBHOST}
      DBUSER: ${DBUSER}
      DBPASSWORD: ${DBPASSWORD}
      DB: ${DB}
      SCHEMA: ${SCHEMA}
      PORT: ${PORT}
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    # container_name: mysql
    command: --authentication_policy=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASSWORD}
      MYSQL_ROOT_PASSWORD: ${DBPASSWORD}
